print(type(None))
print(type(True))
print(type(False))
print(type(1))
print(type(5.3))
print(type(5 + 4j))
print(type([1, 5.3, False, 4]))
print(type((1, True, 3, 5+4j)))
print(type(range(5)))
print(type('Hello'))
print(type(b'a'))
print(type(bytearray([1,2,3])))
print(type(memoryview(bytearray('XYZ', 'utf-8'))))
print(type({'a', 3, True}))
print(type(frozenset({1, 2, 3})))
print(type({'a' : 32}))
